config/routes.rb
Rails.application.routes.draw do
  root to: 'contracts#index'

  devise_for :users, path: '', path_names: { sign_up: 'signup', sign_in: 'signin' }

  resources :contracts, only: [:index, :new, :create, :update]
  get '/contracts/edit/(:id)', to: 'contracts#edit', as: :edit_contract

  resources :vendors, only: [] do
    resources :categories, only: [:index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :vendors
end

app/models/contract.rb
class Contract < ApplicationRecord
  belongs_to :vendor
  belongs_to :category
  belongs_to :user

  validates :costs, numericality: { greater_than: 0, message: 'The cost value is invalid' }
  validates :ends_on, presence: { message: 'Ends On is invalid' }
  validate :ends_on_cannot_be_in_the_past

  def ends_on_cannot_be_in_the_past
    if ends_on.present? && ends_on < Date.today
      errors.add(:ends_on, "Ends On can't be in the past")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :validatable

  validates :full_name, presence: true

has_many :contracts
end

app/models/vendor.rb
class Vendor < ApplicationRecord
  has_and_belongs_to_many :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    vendor = Vendor.find(params[:vendor_id])
    render json: vendor.categories
  end
end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  before_action :authenticate_user!

  def new
    @contract = Contract.new
  end

  def create
    @contract = current_user.contracts.new(contract_params)

    if @contract.save
      flash[:notice] = 'Your contract was added'
      redirect_to action: 'index'
    else
      render 'new'
    end
  end

  def index
    @contracts = current_user.contracts
  end

  def edit
    @contract = current_user.contracts.find(params[:id])
  end

  def update
    @contract = current_user.contracts.find(params[:id])

    if @contract.update(contract_params)
      flash[:notice] = 'Your contract was updated'
      redirect_to action: 'index'
    else
      render 'edit'
    end
  end

  private

  def contract_params
    params.require(:contract).permit(:vendor_id, :category_id, :costs, :ends_on)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contracts/_form.html.erb
<%= form_for(@contract, html: { class: 'form form--contract' }) do |f| %>
  <ul>
    <% @contract.errors.messages.each do |_attribute, messages| %>
      <% messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    <% end %>
  </ul>

  <div class='fields'>
    <%= f.label :vendor, class: 'label' %>
    <div class='custom-select'>
      <%= f.select :vendor_id,
        Vendor.all.collect { |vendor| [vendor.name, vendor.id] },
        { include_blank: true },
        data: { vendor: true }, class: 'input'
      %>
    </div>

    <div class="custom-select <%= 'hidden' unless @contract.vendor %>">
      <%= f.label :category, class: 'label' %>
      <%= f.select :category_id,
        @contract.vendor ? @contract.vendor.categories.collect {|category| [category.name, category.id]} : [],
        { include_blank: true },
        data: { categories: true }, class: 'input'
      %>
    </div>

    <%= f.label :costs, class: 'label' %>
    <%= f.text_field :costs, class: 'input' %>

    <%= f.label :ends_on, class: 'label' %>
    <%= f.text_field :ends_on, class: 'input' %>
  </div>

  <div class="actions">
    <%= f.submit submit, class: 'button submit' %>
  </div>
<% end %>

app/views/contracts/edit.html.erb
<%= render 'form', submit: 'Update' %>

app/views/contracts/index.html.erb
<h2>My contracts</h2>

<%= link_to 'Add Contract', new_contract_path, class: 'button submit space-bottom' %>
<br />

<% if @contracts.empty? %>
  <span class="empty-state">No contracts yet</span>
<% else %>
  <div class='contract-list'>
    <% @contracts.each do |contract| %>
      <%= link_to edit_contract_path(contract), class: 'contract-list--item' do %>
        <div class='contract-list--attribute'>
          <span class='attribute-name'>Vendor</span>
          <%= contract.vendor.name %>
        </div>

        <div class='contract-list--attribute'>
          <span class='attribute-name'>Category</span>
          <%= contract.category.name %>
        </div>

        <div class='contract-list--attribute'>
          <span class='attribute-name'>Cost</span>
          <%= number_to_currency(contract.costs) %>
        </div>

        <div class='contract-list--attribute'>
          <span class='attribute-name'>Ends on</span>
          <%= l contract.ends_on, format: :short %>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/contracts/new.html.erb
<%= render 'form', submit: 'Create' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContractManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class='header'>
      <div class='header-content'>
        <a class='title' href='/' >Contact Manager</a>
        <div class='links'>
          <%= render 'devise/shared/login_itens' %>
        </div>
      </div>

      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </header>
    <div id="container">
      <%= yield %>
    </div>
  </body>
</html>